### ISSUE TITLE
system messages processed as incoming messages

### ISSUE THREAD

**Issue by adbenitez** [deltachat-bot/deltabot#26]
account hook `ac_incoming_message` isn't triggered on member added/removed events, but since deltabot uses `account.get_fresh_messages()` fresh member added/removed events are returned and processed as incoming messages

**Comment by hpk42** [comment]
As discussed on chat, you can call `message.is_system_message()` within a `deltabot_incoming_message` hook implementation. 

see https://py.delta.chat/api.html#deltachat.message.Message.is_system_message
