### ISSUE TITLE
Add new type of command "Dynamic"

### ISSUE THREAD

**Issue by adbenitez** [deltachat-bot/deltabot#28]
The objective is to be able to do something like:
`bot.commands.register(name="/join", func=process_join, type='dynamic')`
Then commands like: /join, /join_g20, /join_c11, are processed by function "process_join" and have payloads "",  "g20" and "c11" respectively.
The use case is to make commands that have arguments easy to use by clicking on them on DC clients that support this feature.

**Comment by hpk42** [comment]
fixed with #37
